# Generated by Django 4.2.4 on 2023-08-29 08:53

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('contacts', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('technician_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WMS.users')),
            ],
        ),
    ]
