# Generated by Django 4.2.4 on 2023-08-31 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
